### ISSUE TITLE
Divorce seems not to work

### ISSUE THREAD

**Issue by gingters** [Buildstarted/LORD#11]
The daily news said

"Seth Able has DIVORCED Your Mom for cheating on him with
  the Bartender! He now sings a song of woe!"

But when trying to flirt with Seth, it still says he has a shiny new ring, and trying to flirt results in "rubbing" him in a disarming way, no further text is displayed, but the daily news show that

"Seth Abel called Clara Oswald a silly wench!".

**Comment by Buildstarted** [comment]
It's weird because he was divorced before and someone married him but i've ensured that the state gets saved to the db instead of just in memory since i think that was the problem
