### ISSUE TITLE
[More] requires multiple key presses

### ISSUE THREAD

**Issue by dustindavis** [Buildstarted/LORD#13]
When prompted to press a key at the [More] prompt, it takes more than 1 key press to activate the action. This does not always happen. It does however always occur during the Forgotten Castle when you are going to receive 5 gems and the Rope.

ATM it doesn't seem to generate an error in the console.

**Comment by dustindavis** [comment]
Could not find Array[2]0: "ForgottenCastle/walkchance4"1: "Main/walkchance4"length: 2__proto__: Array[0]

**Comment by Buildstarted** [comment]
that's because it doesn't exist :)

i'll try to fix this tonight
