### ISSUE TITLE
Dark tavern menu options are incorrect

### ISSUE THREAD

**Issue by dustindavis** [Buildstarted/LORD#14]
In the dark tavern the listing for the available menu options is incorrect.

Dark Cloak Tavern   (? for menu)
  (C,D,F,T,G,V,H,M,R)

there is no F or M or H option and E is missing from the menu so it should be

Dark Cloak Tavern   (? for menu)
  (C,D,E,T,G,V,R)

**Comment by Buildstarted** [comment]
fixed in upcoming release
