### ISSUE TITLE
Quitting doesn't always log user out

### ISSUE THREAD

**Issue by dustindavis** [Buildstarted/LORD#17]
When quitting the game from the main menu by pressing Q, you will end up at the main login screen. By pressing E you will log back in as the previous account. For example, if I logged in via twitter, I will automatically be logged back in under twitter instead of being asked for a login type (i.e. Github of Twitter). 

This can be reproduced by renting a room which sends the user to the initial menu and then pressing E to log in. 

At the initial menu screen you can press Q once more to ensure a log out.

**Comment by Buildstarted** [comment]
Seems to only affect Inn since i don't explicitly log you out there.
