### ISSUE TITLE
Transfer gold is flacky

### ISSUE THREAD

**Issue by gingters** [Buildstarted/LORD#2]
When I want to transfer gold, I chose the amount (i.e. 10k), and then type the name of a character (i.e. Clara). This works, as it suggest the correct character.

After that, I immediately want to transfer another 10 k. So I chose the amount (10k), and then again type 'Clara' for the name. This time, the game does not find the character. Instead, I have to re-select transfer, add the amount a third time, and then, when typing 'Clara', it again finds the char.

Its reproducible: Every time I want to transfer gold from Doctor Who to Clara Oswald twice, on the second try the game does not find the char and I need a third try to finish the transfer.

**Comment by Buildstarted** [comment]
Should have been fixed in a previous release. I'll check again.
