### ISSUE TITLE
Placeholder not replaced when killing enemy with thieving skills

### ISSUE THREAD

**Issue by gingters** [Buildstarted/LORD#26]
When killing an enemy with thieving skills, you may see this text with a non-replaced placeholder for enemy name.

** ULTRA SNEAKY MOVE **

  
  In a swift move you have Angry Liontaur by the neck and begin to
  exert huge amounts of pressure. You hear a sickening crack.

  You hit Angry Liontaur for 1661 damage!

  You have laid this mythical beast to rest.

  You have killed @enemyname!

  You receive 13259 gold, and 753 experience!

  [MORE]

**Comment by Buildstarted** [comment]
fixed and updated - thanks!
