### ISSUE TITLE
Master thief forest event make you stuck

### ISSUE THREAD

**Issue by gingters** [Buildstarted/LORD#8]
There is this special forest event:

Legend Of the Red Dragon - Event in the Forest
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  You are carefully moving through the forest, making absolutely no noise
  when your sensitive ears pick up a twig breaking.  You circle around
  towards the noise, and find it's not an animal, but The Master Thieves!

  As they pass under a tree you are in, you call out. "Ahh... Master
  Thieves!  Do you think it would be possible to make even MORE noise?!"

  The group is very embarrassed, but they overcome it to chew the fat with
  you.

  EXTRA THIEVING USE FOR TODAY!

  [MORE]

After this is shown, no interaction is possible, the character is stuck at this screen.

**Comment by Buildstarted** [comment]
pushed update :)
